controller_list:
  - name: fake_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_hand_controller
    joints:
      - robotiq_85_left_knuckle_joint
initial:  # Define initial robot poses.
  - group: hand
    pose: start